In [1]:
import numpy as np
import pandas as pd
import os
from tqdm import tqdm
import json
import argparse

In [2]:
header = pd.read_csv('data/header.tsv', sep='\t')

In [3]:
df = pd.read_csv('data/sample.tsv', sep='\t', names=header.columns, iterator=True, chunksize=1000)
valid_df = pd.read_csv('data/valid.tsv', sep='\t', names=header.columns, iterator=True, chunksize=1000)

In [4]:
flist = [x for x in list(header.columns) if 'Feature' in x]
id_feature = ["m:AdId", "m:OrderId", "m:CampaignId", "m:AdvertiserId", "m:ClientID", "m:TagId", "m:PublisherFullDomainHash", "m:PublisherId", "m:UserAgentNormalizedHash","m:DeviceOSHash"]

In [5]:
min_list = []
max_list = []
ilen = len(id_feature)
flen = len(flist)
idxdicts = [{} for _ in range(ilen)]
idxrecord = [0] * ilen

In [6]:
idxdicts

[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}]

In [7]:
def get_meta_info(chunk):
    
    global max_list, min_list
    
    cmin_list = []
    cmax_list = []
    for fname in flist:
        cmin_list.append(int(chunk[fname].min()))
        cmax_list.append(int(chunk[fname].max()))
    
    llen = len(max_list)
    if llen == 0:
        min_list = cmin_list
        max_list = cmax_list
    else:
        assert(llen == flen)
        for i in range(llen):
            if cmin_list[i] < min_list[i]:
                min_list[i] = cmin_list[i]
            if cmax_list[i] > max_list[i]:
                max_list[i] = cmax_list[i]
                
    for j in range(ilen):
        idname = id_feature[j]
        for v in chunk[idname]:
            if j == 9:
            if v not in idxdicts[j]:
                idxdicts[j][v] = idxrecord[j]
                idxrecord[j] += 1


In [8]:
for chunk in tqdm(df):
    get_meta_info(chunk)

for chunk in tqdm(valid_df):
    get_meta_info(chunk)

2it [00:00, 12.52it/s]

aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
00000000000000000000000000000000
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
f895df5b37498f660cde1a2388d7af8b
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce

6it [00:00, 11.69it/s]

1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce

10it [00:00, 12.19it/s]


1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
1bdf605991920db11cbdf8508204c4eb
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
edc9f0a5a5d57797bf68e37364743831
e84e30b9390cdb64db6db2c9ab87846d
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce

0it [00:00, ?it/s]

aea23489ce3aa9b6406ebb28e0cda430

2it [00:00, 12.50it/s]


aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
00000000000000000000000000000000
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
f895df5b37498f660cde1a2388d7af8b
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489c

6it [00:00, 13.83it/s]

1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce

10it [00:00, 13.48it/s]

aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
1bdf605991920db11cbdf8508204c4eb
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
f895df5b37498f660cde1a2388d7af8b
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce3aa9b6406ebb28e0cda430
e84e30b9390cdb64db6db2c9ab87846d
aea23489ce3aa9b6406ebb28e0cda430
aea23489ce

In [9]:
idxdicts[8]

{'0e4d943ffd31c695dde3b356cb5fcd7d': 0,
 'a431cbee080e34f5a9796d94404891ab': 1,
 '97845356517bfcd8675c6f75684aa597': 2,
 'd932c2aadb4d273f57d15fe0c2f34719': 3,
 '1d6b8c7f790f3123169d25c77863149e': 4,
 '8139cf8658ad9063eb8df451beb6544f': 5,
 '7d2c45ec642396efe1f18bf44fc07d91': 6,
 '49aa0ffb7504c7895c0e3c3f2f0e8934': 7,
 '28c690d1daf2dc26fa0417462d805652': 8,
 '115d2f18848768628531d9e9426aa939': 9,
 '91a906ca1898fb55902fb8615380223f': 10,
 '03ab21c1fb565afcbf9740586a0bf115': 11,
 '8f2d75e5f98ef8efd2ed66efecd3bb90': 12,
 '8a9e0bd37526f525e633e9d656ff30ff': 13,
 'f55730c6c7e500c142dfd0b87918407b': 14,
 'b1c52555034854c650f90cdf765320f7': 15,
 '132a573f9c9e834c944df8a416b34a6a': 16,
 'bc6c4ea483ff6a3e5cb9fd64c31fcaf8': 17,
 '86f8f9c29decc2e74baaa83e37cd9cc4': 18,
 'caa47365b690b9e3bdffe15baa350a78': 19,
 '17dfac3fc885680ae6d26b1a9a809470': 20,
 '66839a9411a83d7c4fd9e4fecfb7e83a': 21,
 'd8ec921637b6eda14f9b88d66ff2009d': 22,
 'bb55cbb3a0e1a0af2786be000d6b54c0': 23,
 'ffd574101cec5b44c0010b4f

In [11]:
to_minus = []
to_div = []
for i in range(flen):
    if min_list[i] == max_list[i] or (min_list[i] == 0 and max_list[i] == 1):
        to_minus.append(0)
        to_div.append(1)
    else:
        to_minus.append(min_list[i])
        to_div.append(max_list[i] - min_list[i])

infodict = {
    "features": flist,
    "to_minus": to_minus,
    "to_div": to_div,
    "ids": id_feature,
    "dicts": idxdicts
}

In [21]:
df = pd.read_csv('data/sample2.tsv', sep='\t', iterator=True, chunksize=8)

In [22]:
dfiter = iter(df)

In [23]:
while True:
    try:
        cur_chunk = next(dfiter).values
        print(cur_chunk)
    except:
        print('end')
        break

[[    0 17307]
 [    1 10685]
 [    2 17929]
 [    3 13744]
 [    4 14940]
 [    5 16733]
 [    6 19340]
 [    7 17724]]
[[    8 17912]
 [    9 12115]
 [   10 16601]
 [   11 11839]
 [   12 17908]
 [   13 14802]
 [   14 16551]
 [   15 16418]]
[[   16 19340]
 [   17 18807]
 [   18 16137]
 [   19 18797]
 [   20 15484]
 [   21 17620]
 [   22 18552]
 [   23 18418]]
[[   24 18797]
 [   25 20203]
 [   26 13247]
 [   27 20203]
 [   28  5872]
 [   29 17027]
 [   30 17385]
 [   31 19459]]
[[   32 17225]
 [   33 16611]
 [   34 17154]
 [   35 16613]
 [   36 15526]
 [   37 14084]
 [   38  8792]
 [   39 18418]]
[[   40 14413]
 [   41 16955]
 [   42 18807]
 [   43 14950]
 [   44 13334]
 [   45 11898]
 [   46  9576]
 [   47 10544]]
[[   48 16066]
 [   49 15580]
 [   50 16766]
 [   51 17749]
 [   52 17154]
 [   53 17724]
 [   54 16601]
 [   55 18707]]
[[   56 20203]
 [   57 18773]
 [   58 18521]
 [   59 15002]
 [   60 18864]
 [   61 17972]
 [   62 18747]
 [   63 16727]]
[[   64 15154]
 [   65 17189]
 [

[[ 1392 18828]
 [ 1393 17553]
 [ 1394 13500]
 [ 1395 19451]
 [ 1396 14928]
 [ 1397 18773]
 [ 1398 14038]
 [ 1399 18418]]
[[ 1400 15669]
 [ 1401 17164]
 [ 1402 17452]
 [ 1403 15077]
 [ 1404 19459]
 [ 1405 17589]
 [ 1406 16831]
 [ 1407 18521]]
[[ 1408 16300]
 [ 1409 12164]
 [ 1410 19459]
 [ 1411 17313]
 [ 1412 15420]
 [ 1413 17313]
 [ 1414 10316]
 [ 1415 18418]]
[[ 1416 15563]
 [ 1417 17358]
 [ 1418 11515]
 [ 1419 17170]
 [ 1420 18658]
 [ 1421 16178]
 [ 1422 14777]
 [ 1423 18864]]
[[ 1424 13893]
 [ 1425 20203]
 [ 1426 16727]
 [ 1427 16841]
 [ 1428 16995]
 [ 1429 17385]
 [ 1430 15636]
 [ 1431 19340]]
[[ 1432 18457]
 [ 1433 17313]
 [ 1434 14902]
 [ 1435 16021]
 [ 1436 18521]
 [ 1437 17448]
 [ 1438 18807]
 [ 1439 14910]]
[[ 1440 17332]
 [ 1441 15179]
 [ 1442 17005]
 [ 1443 15489]
 [ 1444 18521]
 [ 1445 15496]
 [ 1446 19451]
 [ 1447 18432]]
[[ 1448 18418]
 [ 1449 17912]
 [ 1450 18521]
 [ 1451 18658]
 [ 1452 16733]
 [ 1453 18521]
 [ 1454 15636]
 [ 1455 18747]]
[[ 1456 17861]
 [ 1457 17912]
 [

[[ 2696 18747]
 [ 2697 18460]
 [ 2698 15660]
 [ 2699 18432]
 [ 2700 16332]
 [ 2701 16348]
 [ 2702 15281]
 [ 2703 12085]]
[[ 2704 20203]
 [ 2705 16814]
 [ 2706 12855]
 [ 2707 18747]
 [ 2708 18807]
 [ 2709 13011]
 [ 2710 18773]
 [ 2711 18707]]
[[ 2712 18432]
 [ 2713 13064]
 [ 2714 17963]
 [ 2715 18521]
 [ 2716 18807]
 [ 2717 16491]
 [ 2718 17114]
 [ 2719 12010]]
[[ 2720 19340]
 [ 2721 13475]
 [ 2722 13562]
 [ 2723 16348]
 [ 2724 12834]
 [ 2725 20203]
 [ 2726  5576]
 [ 2727 14317]]
[[ 2728 11896]
 [ 2729 17260]
 [ 2730 18773]
 [ 2731 16060]
 [ 2732 17972]
 [ 2733 17098]
 [ 2734 16568]
 [ 2735 16491]]
[[ 2736 16615]
 [ 2737 18807]
 [ 2738 16841]
 [ 2739 14893]
 [ 2740 14491]
 [ 2741 17850]
 [ 2742 15389]
 [ 2743 15415]]
[[ 2744 17230]
 [ 2745 17082]
 [ 2746 18521]
 [ 2747 13024]
 [ 2748 18807]
 [ 2749 19459]
 [ 2750 12832]
 [ 2751 14277]]
[[ 2752 18457]
 [ 2753 16140]
 [ 2754 14696]
 [ 2755 14436]
 [ 2756 11854]
 [ 2757 17027]
 [ 2758 18828]
 [ 2759 18658]]
[[ 2760 17589]
 [ 2761 16308]
 [

[[ 4136 11905]
 [ 4137 14370]
 [ 4138 16913]
 [ 4139 18418]
 [ 4140 19451]
 [ 4141 18818]
 [ 4142 12624]
 [ 4143 16238]]
[[ 4144 18436]
 [ 4145 18552]
 [ 4146 18864]
 [ 4147 18828]
 [ 4148 15617]
 [ 4149 14928]
 [ 4150 14388]
 [ 4151 16645]]
[[ 4152 14730]
 [ 4153 16340]
 [ 4154 10370]
 [ 4155 16727]
 [ 4156 16941]
 [ 4157 19459]
 [ 4158 14586]
 [ 4159 17260]]
[[ 4160 16611]
 [ 4161 17278]
 [ 4162 15904]
 [ 4163 18418]
 [ 4164 17339]
 [ 4165 19459]
 [ 4166 20203]
 [ 4167 18521]]
[[ 4168 16633]
 [ 4169 15636]
 [ 4170 17963]
 [ 4171 15636]
 [ 4172 16601]
 [ 4173 17963]
 [ 4174 15580]
 [ 4175 16613]]
[[ 4176 18747]
 [ 4177 11775]
 [ 4178 18807]
 [ 4179 17963]
 [ 4180 18432]
 [ 4181 16805]
 [ 4182 13451]
 [ 4183 16611]]
[[ 4184 18807]
 [ 4185 13804]
 [ 4186 15958]
 [ 4187 15406]
 [ 4188 17895]
 [ 4189 16805]
 [ 4190 18432]
 [ 4191 17189]]
[[ 4192 17278]
 [ 4193 15259]
 [ 4194 13632]
 [ 4195 18807]
 [ 4196 16995]
 [ 4197 15528]
 [ 4198 17749]
 [ 4199 17972]]
[[ 4200 17170]
 [ 4201 14809]
 [

[[ 5472 18457]
 [ 5473 15563]
 [ 5474 17972]
 [ 5475 17553]
 [ 5476 12578]
 [ 5477 17971]
 [ 5478 17589]
 [ 5479 14103]]
[[ 5480 18864]
 [ 5481 13033]
 [ 5482 18807]
 [ 5483 12308]
 [ 5484 17260]
 [ 5485 14404]
 [ 5486 16129]
 [ 5487 12272]]
[[ 5488 17895]
 [ 5489 20203]
 [ 5490 11019]
 [ 5491 17762]
 [ 5492 14086]
 [ 5493 17912]
 [ 5494 17589]
 [ 5495 15149]]
[[ 5496 18773]
 [ 5497 15005]
 [ 5498 17241]
 [ 5499 17589]
 [ 5500 16955]
 [ 5501 17972]
 [ 5502 17929]
 [ 5503 14404]]
[[ 5504 17912]
 [ 5505 19459]
 [ 5506 18457]
 [ 5507 14784]
 [ 5508 17238]
 [ 5509 16348]
 [ 5510 11822]
 [ 5511 16931]]
[[ 5512 18707]
 [ 5513 17386]
 [ 5514 16242]
 [ 5515 18658]
 [ 5516 16805]
 [ 5517 17413]
 [ 5518 13761]
 [ 5519 18818]]
[[ 5520 18457]
 [ 5521 18773]
 [ 5522  9474]
 [ 5523 18457]
 [ 5524 18818]
 [ 5525 18773]
 [ 5526 18707]
 [ 5527 18828]]
[[ 5528 16332]
 [ 5529 17914]
 [ 5530 20203]
 [ 5531 18457]
 [ 5532 15039]
 [ 5533 16841]
 [ 5534 15967]
 [ 5535 14765]]
[[ 5536 17908]
 [ 5537 20203]
 [

[[ 6104 18734]
 [ 6105 16251]
 [ 6106 13929]
 [ 6107 18818]
 [ 6108 17241]
 [ 6109 18864]
 [ 6110 18552]
 [ 6111 16175]]
[[ 6112 18432]
 [ 6113 17339]
 [ 6114 18828]
 [ 6115 18773]
 [ 6116 19451]
 [ 6117 16855]
 [ 6118 15425]
 [ 6119 18828]]
[[ 6120 17670]
 [ 6121 15106]
 [ 6122 14586]
 [ 6123 17929]
 [ 6124 17749]
 [ 6125 19459]
 [ 6126 18521]
 [ 6127 10885]]
[[ 6128 18773]
 [ 6129 19340]
 [ 6130 17601]
 [ 6131 15959]
 [ 6132 18828]
 [ 6133 18432]
 [ 6134 15259]
 [ 6135 19451]]
[[ 6136 17332]
 [ 6137 15224]
 [ 6138 18797]
 [ 6139 13842]
 [ 6140 15420]
 [ 6141 16051]
 [ 6142 17589]
 [ 6143 10476]]
[[ 6144 17225]
 [ 6145 15904]
 [ 6146 20203]
 [ 6147 16922]
 [ 6148 16238]
 [ 6149 19451]
 [ 6150 17670]
 [ 6151 13688]]
[[ 6152 16955]
 [ 6153 15520]
 [ 6154 19451]
 [ 6155 12263]
 [ 6156 12993]
 [ 6157 16931]
 [ 6158 17307]
 [ 6159 14333]]
[[ 6160 12383]
 [ 6161 14103]
 [ 6162 13596]
 [ 6163 18773]
 [ 6164 14612]
 [ 6165 18521]
 [ 6166 16175]
 [ 6167 17037]]
[[ 6168 13911]
 [ 6169 17749]
 [

[[ 6864 14444]
 [ 6865 17718]
 [ 6866 15265]
 [ 6867 16066]
 [ 6868 10988]
 [ 6869 17589]
 [ 6870 19340]
 [ 6871 18807]]
[[ 6872 19340]
 [ 6873 18807]
 [ 6874 15634]
 [ 6875 16766]
 [ 6876 17170]
 [ 6877 16978]
 [ 6878 18807]
 [ 6879  8251]]
[[ 6880 19340]
 [ 6881 18521]
 [ 6882 17908]
 [ 6883 16479]
 [ 6884 19340]
 [ 6885 14479]
 [ 6886 18521]
 [ 6887  6389]]
[[ 6888 15698]
 [ 6889 16131]
 [ 6890 13555]
 [ 6891 17225]
 [ 6892 16175]
 [ 6893 14140]
 [ 6894 18773]
 [ 6895 17971]]
[[ 6896 11171]
 [ 6897 19451]
 [ 6898 16841]
 [ 6899 17912]
 [ 6900 12101]
 [ 6901 15997]
 [ 6902 16162]
 [ 6903 17098]]
[[ 6904 20203]
 [ 6905 17912]
 [ 6906 16814]
 [ 6907 13992]
 [ 6908 18828]
 [ 6909 15309]
 [ 6910 16841]
 [ 6911 16129]]
[[ 6912 18457]
 [ 6913 16805]
 [ 6914 17032]
 [ 6915 16841]
 [ 6916 19459]
 [ 6917 17047]
 [ 6918 15654]
 [ 6919 15817]]
[[ 6920 18773]
 [ 6921  3912]
 [ 6922 18552]
 [ 6923 10423]
 [ 6924 16615]
 [ 6925 16978]
 [ 6926 18521]
 [ 6927 17972]]
[[ 6928 15610]
 [ 6929 18521]
 [

[[ 7632 17005]
 [ 7633 15356]
 [ 7634 14647]
 [ 7635 16814]
 [ 7636 18734]
 [ 7637 16934]
 [ 7638 17914]
 [ 7639 17929]]
[[ 7640 17045]
 [ 7641 19340]
 [ 7642 17339]
 [ 7643 17313]
 [ 7644 12812]
 [ 7645 19340]
 [ 7646 18521]
 [ 7647 18807]]
[[ 7648 15393]
 [ 7649 18773]
 [ 7650 16934]
 [ 7651 20203]
 [ 7652 17448]
 [ 7653 20203]
 [ 7654 17589]
 [ 7655 17313]]
[[ 7656 13630]
 [ 7657 14084]
 [ 7658  8392]
 [ 7659 12943]
 [ 7660 16178]
 [ 7661 19459]
 [ 7662 13682]
 [ 7663 19451]]
[[ 7664  9335]
 [ 7665 16841]
 [ 7666 12747]
 [ 7667 17005]
 [ 7668 17724]
 [ 7669 18460]
 [ 7670 17307]
 [ 7671 19340]]
[[ 7672 16784]
 [ 7673 20203]
 [ 7674 20203]
 [ 7675 18864]
 [ 7676 19340]
 [ 7677 11266]
 [ 7678 18747]
 [ 7679 17963]]
[[ 7680 17164]
 [ 7681 19340]
 [ 7682 15265]
 [ 7683 17339]
 [ 7684 17238]
 [ 7685 15804]
 [ 7686 16131]
 [ 7687 18521]]
[[ 7688 17226]
 [ 7689 16814]
 [ 7690 17322]
 [ 7691 19340]
 [ 7692 16766]
 [ 7693 16021]
 [ 7694 11833]
 [ 7695 14288]]
[[ 7696 17260]
 [ 7697 17762]
 [

[[ 8464 18818]
 [ 8465 17045]
 [ 8466 17322]
 [ 8467 16251]
 [ 8468 13761]
 [ 8469 16479]
 [ 8470 18658]
 [ 8471 20203]]
[[ 8472 17850]
 [ 8473  6666]
 [ 8474 17908]
 [ 8475 18418]
 [ 8476 18864]
 [ 8477 16585]
 [ 8478 19340]
 [ 8479 16568]]
[[ 8480  9288]
 [ 8481 17912]
 [ 8482 16303]
 [ 8483 12486]
 [ 8484 18460]
 [ 8485 18818]
 [ 8486 18457]
 [ 8487 18818]]
[[ 8488 18218]
 [ 8489 17358]
 [ 8490 19451]
 [ 8491 18460]
 [ 8492 18457]
 [ 8493 17238]
 [ 8494 20203]
 [ 8495 16202]]
[[ 8496 16764]
 [ 8497 16733]
 [ 8498 16436]
 [ 8499 19451]
 [ 8500 18658]
 [ 8501 15655]
 [ 8502 17385]
 [ 8503  9697]]
[[ 8504 20203]
 [ 8505 15044]
 [ 8506 14921]
 [ 8507 17339]
 [ 8508  3912]
 [ 8509 16601]
 [ 8510 16867]
 [ 8511 15526]]
[[ 8512 15420]
 [ 8513 18432]
 [ 8514 17670]
 [ 8515 17762]
 [ 8516 18807]
 [ 8517 18457]
 [ 8518 15415]
 [ 8519 17908]]
[[ 8520 15753]
 [ 8521 17045]
 [ 8522 17601]
 [ 8523 15496]
 [ 8524 18807]
 [ 8525 15259]
 [ 8526 17724]
 [ 8527 18457]]
[[ 8528 17592]
 [ 8529 18457]
 [

[[ 9688 15655]
 [ 9689 17929]
 [ 9690 17452]
 [ 9691 15389]
 [ 9692 17045]
 [ 9693 17230]
 [ 9694 16727]
 [ 9695 16436]]
[[ 9696 18460]
 [ 9697 16613]
 [ 9698 17241]
 [ 9699 19451]
 [ 9700 14156]
 [ 9701 17225]
 [ 9702 15763]
 [ 9703 18818]]
[[ 9704 13842]
 [ 9705 15303]
 [ 9706 18436]
 [ 9707 16841]
 [ 9708 17749]
 [ 9709 16934]
 [ 9710 16597]
 [ 9711 18521]]
[[ 9712 13764]
 [ 9713 14928]
 [ 9714 15511]
 [ 9715 15753]
 [ 9716 17861]
 [ 9717 17724]
 [ 9718 19451]
 [ 9719 17929]]
[[ 9720 19459]
 [ 9721 15753]
 [ 9722 18797]
 [ 9723 17005]
 [ 9724 14559]
 [ 9725 18521]
 [ 9726 16941]
 [ 9727 14769]]
[[ 9728 15522]
 [ 9729 18828]
 [ 9730 18658]
 [ 9731 20203]
 [ 9732 19340]
 [ 9733 15573]
 [ 9734 20203]
 [ 9735 20203]]
[[ 9736 17045]
 [ 9737 11905]
 [ 9738 17260]
 [ 9739 19340]
 [ 9740 18658]
 [ 9741 16919]
 [ 9742 19459]
 [ 9743 18818]]
[[ 9744 18818]
 [ 9745 15972]
 [ 9746 17912]
 [ 9747 18521]
 [ 9748 17406]
 [ 9749 19459]
 [ 9750 14736]
 [ 9751 16841]]
[[ 9752 16348]
 [ 9753 18734]
 [