In [6]:
import numpy as np
import pandas as pd
import os
from tqdm import tqdm
import json

In [7]:
datap = "data"

In [8]:
filep = os.path.join(datap, "sample.tsv")
outp = os.path.join(datap, "meta_info.json")

In [9]:
header = pd.read_csv('data/header.tsv', sep='\t')
df = pd.read_csv('data/sample.tsv', sep='\t', names=header.columns)

In [12]:
header.drop(columns=id_feature)

Empty DataFrame
Columns: [Feature_7604_garbage1_none, Feature_7604_Impressions_log, Feature_7604_NonClicksByClicksWithGBin_customizedlog, Feature_1_garbage1_none, Feature_1_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_66_garbage1_none, Feature_66_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_66_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_105_garbage1_none, Feature_105_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_105_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_163_garbage1_none, Feature_163_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_163_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_416_garbage1_none, Feature_416_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_416_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_552_garbage1_none, Feature_552_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_552_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_594_garbage1_none, Feature_594_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_594_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_755_garbage1_none, Feature_755_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_755_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_756_garbage1_none, Feature_756_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_756_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1057_garbage1_none, Feature_1057_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1057_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1167_garbage1_none, Feature_1167_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1167_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1168_garbage1_none, Feature_1168_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1168_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1341_garbage1_none, Feature_1341_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1341_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1361_garbage1_none, Feature_1361_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1361_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1371_garbage1_none, Feature_1371_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1371_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1385_garbage1_none, Feature_1385_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1385_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1388_garbage1_none, Feature_1388_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1388_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1399_garbage1_none, Feature_1399_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1399_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1461_garbage1_none, Feature_1461_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1461_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1574_garbage1_none, Feature_1574_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1574_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1576_garbage1_none, Feature_1576_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1576_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1627_garbage1_none, Feature_1627_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1627_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1628_garbage1_none, Feature_1628_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1628_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_1631_garbage1_none, Feature_1631_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_1631_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_678_garbage1_none, Feature_678_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_678_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_905_garbage1_none, Feature_905_COECUsingClicks_add1thenlogthenmultiplyby1000, Feature_905_ExpectedClicks_add1thenlogthenmultiplyby1000, Feature_2600_garbage1_none, Feature_2600_COECUsingClicks_add1thenlogthenmultiplyby

In [16]:
df

Feature_7604_garbage1_none  Feature_7604_Impressions_log  \
0                              0                         17307   
1                              0                         10685   
2                              0                         17929   
3                              0                         13744   
4                              0                         14940   
...                          ...                           ...   
9995                           0                         17912   
9996                           0                         16251   
9997                           0                         17971   
9998                           0                         16601   
9999                           0                         15779   

      Feature_7604_NonClicksByClicksWithGBin_customizedlog  \
0                                                  5430      
1                                                  6007      
2                                                  5785      
3                                                  5539      
4                                                  5190      
...                                                 ...      
9995                                               5895      
9996                                               5809      
9997                                               5379      
9998                                               5492      
9999                                               4153      

      Feature_1_garbage1_none  \
0                           0   
1                           0   
2                           1   
3                           0   
4                           1   
...                       ...   
9995                        0   
9996                        0   
9997                        0   
9998                        1   
9999                        0   

      Feature_1_COECUsingClicks_add1thenlogthenmultiplyby1000  \
0                                                   334         
1                                                   329         
2                                                   611         
3                                                   713         
4                                                   611         
...                                                 ...         
9995                                                394         
9996                                                432         
9997                                                566         
9998                                                611         
9999                                                942         

      Feature_1_ExpectedClicks_add1thenlogthenmultiplyby1000  \
0                                                  1616        
1                                                   939        
2                                                    95        
3                                                  3426        
4                                                    95        
...                                                 ...        
9995                                               1823        
9996                                                613        
9997                                                963        
9998                                                 95        
9999                                               1161        

      Feature_66_garbage1_none  \
0                            0   
1                            1   
2                            1   
3                            1   
4                            0   
...                        ...   
9995                         0   
9996                         0   
9997                         0   
9998                         0   
9999                         1   

      Feature_66_COECUsingClicks_add1thenlogthenmultiplyby1000  \
0                                             

In [7]:
flist = [x for x in list(header.columns) if 'Feature' in x]

In [22]:
flist = ["Feature_1_garbage1_none",
"Feature_1_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_1_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_66_garbage1_none",
"Feature_66_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_66_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_552_garbage1_none",
"Feature_552_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_552_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_594_garbage1_none",
"Feature_594_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_594_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_755_garbage1_none",
"Feature_755_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_755_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_1574_garbage1_none",
"Feature_1574_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_1574_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_1576_garbage1_none",
"Feature_1576_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_1576_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_1627_garbage1_none",
"Feature_1627_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_1627_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_1628_garbage1_none",
"Feature_1628_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_1628_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_1631_garbage1_none",
"Feature_1631_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_1631_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_25_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_25_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_97_garbage1_none",
"Feature_97_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_97_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_576_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_576_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_181_garbage1_none",
"Feature_181_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_181_ExpectedClicks_add1thenlogthenmultiplyby1000",
# "Feature_Cascade_7",
"Feature_66_garbage1_none_5",
"Feature_66_RTImpressions_add1thenlogthenmultiplyby1000_5",
"Feature_66_RTNonClicksByClicks_add1thenlogthenmultiplyby1000_5",
"Feature_7276_garbage1_none_5",
"Feature_7276_RTImpressions_add1thenlogthenmultiplyby1000_5",
"Feature_7276_RTNonClicksByClicks_add1thenlogthenmultiplyby1000_5",
"Feature_1_garbage1_none_5",
"Feature_1_RTImpressions_add1thenlogthenmultiplyby1000_5",
"Feature_1_RTNonClicksByClicks_add1thenlogthenmultiplyby1000_5",
"Feature_1194_garbage1_none_5",
"Feature_1194_RTImpressions_add1thenlogthenmultiplyby1000_5",
"Feature_1194_RTNonClicksByClicks_add1thenlogthenmultiplyby1000_5",
"Feature_163_garbage1_none_5",
"Feature_163_RTImpressions_add1thenlogthenmultiplyby1000_5",
"Feature_163_RTNonClicksByClicks_add1thenlogthenmultiplyby1000_5",
"Feature_7240_garbage1_none_5",
"Feature_7240_RTImpressions_add1thenlogthenmultiplyby1000_5",
"Feature_7240_RTNonClicksByClicks_add1thenlogthenmultiplyby1000_5"
]

In [25]:
df[flist]

Feature_1_garbage1_none  \
0                           0   
1                           0   
2                           1   
3                           0   
4                           1   
...                       ...   
9995                        0   
9996                        0   
9997                        0   
9998                        1   
9999                        0   

      Feature_1_COECUsingClicks_add1thenlogthenmultiplyby1000  \
0                                                   334         
1                                                   329         
2                                                   611         
3                                                   713         
4                                                   611         
...                                                 ...         
9995                                                394         
9996                                                432         
9997                                                566         
9998                                                611         
9999                                                942         

      Feature_1_ExpectedClicks_add1thenlogthenmultiplyby1000  \
0                                                  1616        
1                                                   939        
2                                                    95        
3                                                  3426        
4                                                    95        
...                                                 ...        
9995                                               1823        
9996                                                613        
9997                                                963        
9998                                                 95        
9999                                               1161        

      Feature_66_garbage1_none  \
0                            0   
1                            1   
2                            1   
3                            1   
4                            0   
...                        ...   
9995                         0   
9996                         0   
9997                         0   
9998                         0   
9999                         1   

      Feature_66_COECUsingClicks_add1thenlogthenmultiplyby1000  \
0                                                   483          
1                                                   640          
2                                                   640          
3                                                   640          
4                                                  1063          
...                                                 ...          
9995                                                676          
9996                                                376          
9997                                                566          
9998                                                357          
9999                                                640          

      Feature_66_ExpectedClicks_add1thenlogthenmultiplyby1000  \
0                                                  1168         
1                                                    95         
2                                                    95         
3                                                    95         
4                                                  1151         
...                                                 ...         
9995                                               1132         
9996                                                783         
9997                                                963         
9998                                                844         
9999                                                 95         

      Feature_552_garbage1_none  \
0                             0   
1     

In [26]:
len(flist)

58

In [27]:
for fname in flist:
    print(fname)
    vc = df[fname].value_counts()
    if vc.shape[0] < 10:
        print(vc)

Feature_1_garbage1_none
0    7171
1    2829
Name: Feature_1_garbage1_none, dtype: int64
Feature_1_COECUsingClicks_add1thenlogthenmultiplyby1000
Feature_1_ExpectedClicks_add1thenlogthenmultiplyby1000
Feature_66_garbage1_none
1    5863
0    4137
Name: Feature_66_garbage1_none, dtype: int64
Feature_66_COECUsingClicks_add1thenlogthenmultiplyby1000
Feature_66_ExpectedClicks_add1thenlogthenmultiplyby1000
Feature_552_garbage1_none
0    9710
1     290
Name: Feature_552_garbage1_none, dtype: int64
Feature_552_COECUsingClicks_add1thenlogthenmultiplyby1000
Feature_552_ExpectedClicks_add1thenlogthenmultiplyby1000
Feature_594_garbage1_none
1    9974
0      26
Name: Feature_594_garbage1_none, dtype: int64
Feature_594_COECUsingClicks_add1thenlogthenmultiplyby1000
Feature_594_ExpectedClicks_add1thenlogthenmultiplyby1000
Feature_755_garbage1_none
0    9790
1     210
Name: Feature_755_garbage1_none, dtype: int64
Feature_755_COECUsingClicks_add1thenlogthenmultiplyby1000
Feature_755_ExpectedClicks_add1the

In [28]:
df['Feature_7604_garbage1_none'].value_counts()

0    9985
1      15
Name: Feature_7604_garbage1_none, dtype: int64

In [29]:
clist = list(df.columns)
clist

['Feature_7604_garbage1_none',
 'Feature_7604_Impressions_log',
 'Feature_7604_NonClicksByClicksWithGBin_customizedlog',
 'Feature_1_garbage1_none',
 'Feature_1_COECUsingClicks_add1thenlogthenmultiplyby1000',
 'Feature_1_ExpectedClicks_add1thenlogthenmultiplyby1000',
 'Feature_66_garbage1_none',
 'Feature_66_COECUsingClicks_add1thenlogthenmultiplyby1000',
 'Feature_66_ExpectedClicks_add1thenlogthenmultiplyby1000',
 'Feature_105_garbage1_none',
 'Feature_105_COECUsingClicks_add1thenlogthenmultiplyby1000',
 'Feature_105_ExpectedClicks_add1thenlogthenmultiplyby1000',
 'Feature_163_garbage1_none',
 'Feature_163_COECUsingClicks_add1thenlogthenmultiplyby1000',
 'Feature_163_ExpectedClicks_add1thenlogthenmultiplyby1000',
 'Feature_416_garbage1_none',
 'Feature_416_COECUsingClicks_add1thenlogthenmultiplyby1000',
 'Feature_416_ExpectedClicks_add1thenlogthenmultiplyby1000',
 'Feature_552_garbage1_none',
 'Feature_552_COECUsingClicks_add1thenlogthenmultiplyby1000',
 'Feature_552_ExpectedClicks_ad

In [30]:
flist = [x for x in list(df.columns) if 'Feature' in x]

In [31]:
df[flist].isnull().sum().sum()

0

In [32]:
meta_dict = {}
for fname in flist:
    meta_dict[fname] = {}
    meta_dict[fname]['min'] = df[fname].min()
    meta_dict[fname]['max'] = df[fname].max()

In [33]:
meta_dict

{'Feature_7604_garbage1_none': {'min': 0, 'max': 1},
 'Feature_7604_Impressions_log': {'min': 3912, 'max': 20203},
 'Feature_7604_NonClicksByClicksWithGBin_customizedlog': {'min': 1750,
  'max': 11346},
 'Feature_1_garbage1_none': {'min': 0, 'max': 1},
 'Feature_1_COECUsingClicks_add1thenlogthenmultiplyby1000': {'min': 12,
  'max': 2632},
 'Feature_1_ExpectedClicks_add1thenlogthenmultiplyby1000': {'min': 95,
  'max': 13338},
 'Feature_66_garbage1_none': {'min': 0, 'max': 1},
 'Feature_66_COECUsingClicks_add1thenlogthenmultiplyby1000': {'min': 20,
  'max': 2432},
 'Feature_66_ExpectedClicks_add1thenlogthenmultiplyby1000': {'min': 80,
  'max': 5841},
 'Feature_105_garbage1_none': {'min': 0, 'max': 1},
 'Feature_105_COECUsingClicks_add1thenlogthenmultiplyby1000': {'min': 96,
  'max': 1855},
 'Feature_105_ExpectedClicks_add1thenlogthenmultiplyby1000': {'min': 95,
  'max': 12972},
 'Feature_163_garbage1_none': {'min': 0, 'max': 1},
 'Feature_163_COECUsingClicks_add1thenlogthenmultiplyby1000

In [34]:
min_list = []
max_list = []
for fname in flist:
    min_list.append(int(df[fname].min()))
    max_list.append(int(df[fname].max()))

In [35]:
min_list

[0,
 3912,
 1750,
 0,
 12,
 95,
 0,
 20,
 80,
 0,
 96,
 95,
 0,
 80,
 95,
 0,
 37,
 87,
 0,
 84,
 95,
 0,
 178,
 52,
 0,
 83,
 95,
 0,
 96,
 95,
 0,
 94,
 95,
 0,
 77,
 95,
 0,
 134,
 95,
 0,
 64,
 95,
 0,
 345,
 5634,
 0,
 662,
 14305,
 0,
 339,
 4124,
 0,
 12,
 95,
 0,
 90,
 2078,
 0,
 76,
 95,
 0,
 64,
 95,
 0,
 55,
 95,
 0,
 67,
 95,
 0,
 66,
 95,
 0,
 67,
 95,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 499,
 8219,
 0,
 672,
 18006,
 0,
 631,
 6361,
 0,
 94,
 95,
 0,
 4,
 95,
 0,
 675,
 14650,
 0,
 605,
 12086,
 0,
 591,
 6361,
 0,
 514,
 6261,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 693,
 693,
 0,
 693,
 693,
 0,
 693,
 693,
 0,
 693,
 693,
 0,
 693,
 693,
 0,
 693,
 693]

In [50]:
header = pd.read_csv('data/header.tsv', sep='\t')
df = pd.read_csv('data/sample.tsv', sep='\t', names=header.columns)

In [10]:
id_feature = ["m:AdId", "m:OrderId", "m:CampaignId", "m:AdvertiserId", "m:ClientID", "m:TagId", "m:PublisherFullDomainHash", "m:PublisherId", "m:UserAgentNormalizedHash","m:DeviceOSHash"]

In [52]:
df[id_feature].values[0]

array([76965978384849, 1231453253691878, 401547031, 1757703,
       '2be2d56ca79d6f7d297cdbaca6616e97', 1059660833, 3149244597,
       17160724, '0e4d943ffd31c695dde3b356cb5fcd7d',
       'aea23489ce3aa9b6406ebb28e0cda430'], dtype=object)

In [53]:
idxdicts = []
for idname in tqdm(id_feature):
    cdict = {}
    idx = 0
    for v in df[idname]:
        if v not in cdict:
            cdict[v] = idx
            idx += 1
    idxdicts.append(cdict)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 266.86it/s]


In [54]:
for index, idname in enumerate(id_feature):
    cdict = idxdicts[index]
    df[idname] = df[idname].map(cdict)

In [56]:
id_indexes = np.arange(len(flist), len(flist + id_feature))
id_indexes

array([164, 165, 166, 167, 168, 169, 170, 171, 172, 173])

In [55]:
df["m:PublisherFullDomainHash"]

0       0
1       0
2       0
3       0
4       0
       ..
9995    0
9996    0
9997    0
9998    0
9999    1
Name: m:PublisherFullDomainHash, Length: 10000, dtype: int64

In [41]:
infodict = {
    "faetures": flist,
    "minlist": min_list,
    "maxlist": max_list,
    "ids": id_feature,
    "dicts": idxdicts
}

In [34]:
json.dump(infodict, open(outp, "w"))

In [40]:
import torch.nn as nn

/home/hu/anaconda3/envs/cv/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [42]:
embs = nn.ModuleList([nn.Embedding(len(d), 20) for d in infodict['dicts']])

In [44]:
len(infodict['dicts'])

10

In [43]:
import torch

In [45]:
c = torch.randint(20, (32, 10))

In [49]:
embs[0](c[:, 0]).size()

torch.Size([32, 20])

In [5]:
df['m:Click'].sum()

54

In [88]:
label = torch.randint(0, 2, (32,)).type(torch.FloatTensor)

In [89]:
label

tensor([1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
        1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0.])

In [90]:
weight = torch.clone(label)
weight.masked_fill_(~weight.type(torch.BoolTensor), 1/20)

tensor([1.0000, 0.0500, 0.0500, 1.0000, 0.0500, 0.0500, 1.0000, 1.0000, 0.0500,
        1.0000, 1.0000, 1.0000, 1.0000, 0.0500, 1.0000, 1.0000, 0.0500, 1.0000,
        1.0000, 0.0500, 0.0500, 1.0000, 0.0500, 1.0000, 1.0000, 0.0500, 0.0500,
        0.0500, 0.0500, 1.0000, 1.0000, 0.0500])

In [91]:
weight

tensor([1.0000, 0.0500, 0.0500, 1.0000, 0.0500, 0.0500, 1.0000, 1.0000, 0.0500,
        1.0000, 1.0000, 1.0000, 1.0000, 0.0500, 1.0000, 1.0000, 0.0500, 1.0000,
        1.0000, 0.0500, 0.0500, 1.0000, 0.0500, 1.0000, 1.0000, 0.0500, 0.0500,
        0.0500, 0.0500, 1.0000, 1.0000, 0.0500])

In [92]:
label

tensor([1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
        1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0.])