In [1]:
import numpy as np
import pandas as pd
import os
from tqdm import tqdm
import json

In [2]:
datap = "data"

In [3]:
filep = os.path.join(datap, "sample.tsv")
outp = os.path.join(datap, "meta_info.json")

In [5]:
header = pd.read_csv('data/header.tsv', sep='\t')
df = pd.read_csv('data/sample.tsv', sep='\t', names=header.columns)

In [16]:
df

Feature_7604_garbage1_none  Feature_7604_Impressions_log  \
0                              0                         17307   
1                              0                         10685   
2                              0                         17929   
3                              0                         13744   
4                              0                         14940   
...                          ...                           ...   
9995                           0                         17912   
9996                           0                         16251   
9997                           0                         17971   
9998                           0                         16601   
9999                           0                         15779   

      Feature_7604_NonClicksByClicksWithGBin_customizedlog  \
0                                                  5430      
1                                                  6007      
2                                                  5785      
3                                                  5539      
4                                                  5190      
...                                                 ...      
9995                                               5895      
9996                                               5809      
9997                                               5379      
9998                                               5492      
9999                                               4153      

      Feature_1_garbage1_none  \
0                           0   
1                           0   
2                           1   
3                           0   
4                           1   
...                       ...   
9995                        0   
9996                        0   
9997                        0   
9998                        1   
9999                        0   

      Feature_1_COECUsingClicks_add1thenlogthenmultiplyby1000  \
0                                                   334         
1                                                   329         
2                                                   611         
3                                                   713         
4                                                   611         
...                                                 ...         
9995                                                394         
9996                                                432         
9997                                                566         
9998                                                611         
9999                                                942         

      Feature_1_ExpectedClicks_add1thenlogthenmultiplyby1000  \
0                                                  1616        
1                                                   939        
2                                                    95        
3                                                  3426        
4                                                    95        
...                                                 ...        
9995                                               1823        
9996                                                613        
9997                                                963        
9998                                                 95        
9999                                               1161        

      Feature_66_garbage1_none  \
0                            0   
1                            1   
2                            1   
3                            1   
4                            0   
...                        ...   
9995                         0   
9996                         0   
9997                         0   
9998                         0   
9999                         1   

      Feature_66_COECUsingClicks_add1thenlogthenmultiplyby1000  \
0                                             

In [7]:
flist = [x for x in list(header.columns) if 'Feature' in x]

In [18]:
flist = ["Feature_1_garbage1_none",
"Feature_1_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_1_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_66_garbage1_none",
"Feature_66_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_66_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_552_garbage1_none",
"Feature_552_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_552_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_594_garbage1_none",
"Feature_594_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_594_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_755_garbage1_none",
"Feature_755_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_755_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_1574_garbage1_none",
"Feature_1574_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_1574_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_1576_garbage1_none",
"Feature_1576_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_1576_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_1627_garbage1_none",
"Feature_1627_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_1627_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_1628_garbage1_none",
"Feature_1628_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_1628_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_1631_garbage1_none",
"Feature_1631_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_1631_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_25_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_25_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_97_garbage1_none",
"Feature_97_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_97_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_576_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_576_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_181_garbage1_none",
"Feature_181_COECUsingClicks_add1thenlogthenmultiplyby1000",
"Feature_181_ExpectedClicks_add1thenlogthenmultiplyby1000",
"Feature_Cascade_7",
"Feature_66_garbage1_none_5",
"Feature_66_RTImpressions_add1thenlogthenmultiplyby1000_5",
"Feature_66_RTNonClicksByClicks_add1thenlogthenmultiplyby1000_5",
"Feature_7276_garbage1_none_5",
"Feature_7276_RTImpressions_add1thenlogthenmultiplyby1000_5",
"Feature_7276_RTNonClicksByClicks_add1thenlogthenmultiplyby1000_5",
"Feature_1_garbage1_none_5",
"Feature_1_RTImpressions_add1thenlogthenmultiplyby1000_5",
"Feature_1_RTNonClicksByClicks_add1thenlogthenmultiplyby1000_5",
"Feature_1194_garbage1_none_5",
"Feature_1194_RTImpressions_add1thenlogthenmultiplyby1000_5",
"Feature_1194_RTNonClicksByClicks_add1thenlogthenmultiplyby1000_5",
"Feature_163_garbage1_none_5",
"Feature_163_RTImpressions_add1thenlogthenmultiplyby1000_5",
"Feature_163_RTNonClicksByClicks_add1thenlogthenmultiplyby1000_5",
"Feature_7240_garbage1_none_5",
"Feature_7240_RTImpressions_add1thenlogthenmultiplyby1000_5",
"Feature_7240_RTNonClicksByClicks_add1thenlogthenmultiplyby1000_5"
]

In [19]:
df[flist]

Feature_1_garbage1_none  \
0                           0   
1                           0   
2                           1   
3                           0   
4                           1   
...                       ...   
9995                        0   
9996                        0   
9997                        0   
9998                        1   
9999                        0   

      Feature_1_COECUsingClicks_add1thenlogthenmultiplyby1000  \
0                                                   334         
1                                                   329         
2                                                   611         
3                                                   713         
4                                                   611         
...                                                 ...         
9995                                                394         
9996                                                432         
9997                                                566         
9998                                                611         
9999                                                942         

      Feature_1_ExpectedClicks_add1thenlogthenmultiplyby1000  \
0                                                  1616        
1                                                   939        
2                                                    95        
3                                                  3426        
4                                                    95        
...                                                 ...        
9995                                               1823        
9996                                                613        
9997                                                963        
9998                                                 95        
9999                                               1161        

      Feature_66_garbage1_none  \
0                            0   
1                            1   
2                            1   
3                            1   
4                            0   
...                        ...   
9995                         0   
9996                         0   
9997                         0   
9998                         0   
9999                         1   

      Feature_66_COECUsingClicks_add1thenlogthenmultiplyby1000  \
0                                                   483          
1                                                   640          
2                                                   640          
3                                                   640          
4                                                  1063          
...                                                 ...          
9995                                                676          
9996                                                376          
9997                                                566          
9998                                                357          
9999                                                640          

      Feature_66_ExpectedClicks_add1thenlogthenmultiplyby1000  
0                                                  1168        
1                                                    95        
2                                                    95        
3                                                    95        
4                                                  1151        
...                                                 ...        
9995                                               1132        
9996                                                783        
9997                                                963        
9998                                                844        
9999                                                 95        

[10000 rows x 6 columns]

In [17]:
len(flist)

164

In [13]:
for fname in flist:
    print(fname)
    vc = df[fname].value_counts()
    if vc.shape[0] < 10:
        print(vc)

Feature_7604_garbage1_none
0    9985
1      15
Name: Feature_7604_garbage1_none, dtype: int64
Feature_7604_Impressions_log
Feature_7604_NonClicksByClicksWithGBin_customizedlog
Feature_1_garbage1_none
0    7171
1    2829
Name: Feature_1_garbage1_none, dtype: int64
Feature_1_COECUsingClicks_add1thenlogthenmultiplyby1000
Feature_1_ExpectedClicks_add1thenlogthenmultiplyby1000
Feature_66_garbage1_none
1    5863
0    4137
Name: Feature_66_garbage1_none, dtype: int64
Feature_66_COECUsingClicks_add1thenlogthenmultiplyby1000
Feature_66_ExpectedClicks_add1thenlogthenmultiplyby1000
Feature_105_garbage1_none
0    9960
1      40
Name: Feature_105_garbage1_none, dtype: int64
Feature_105_COECUsingClicks_add1thenlogthenmultiplyby1000
Feature_105_ExpectedClicks_add1thenlogthenmultiplyby1000
Feature_163_garbage1_none
0    9810
1     190
Name: Feature_163_garbage1_none, dtype: int64
Feature_163_COECUsingClicks_add1thenlogthenmultiplyby1000
Feature_163_ExpectedClicks_add1thenlogthenmultiplyby1000
Feature_

In [10]:
df['Feature_7604_garbage1_none'].value_counts()

0    9985
1      15
Name: Feature_7604_garbage1_none, dtype: int64

In [12]:
clist = list(df.columns)
clist

['Feature_7604_garbage1_none',
 'Feature_7604_Impressions_log',
 'Feature_7604_NonClicksByClicksWithGBin_customizedlog',
 'Feature_1_garbage1_none',
 'Feature_1_COECUsingClicks_add1thenlogthenmultiplyby1000',
 'Feature_1_ExpectedClicks_add1thenlogthenmultiplyby1000',
 'Feature_66_garbage1_none',
 'Feature_66_COECUsingClicks_add1thenlogthenmultiplyby1000',
 'Feature_66_ExpectedClicks_add1thenlogthenmultiplyby1000',
 'Feature_105_garbage1_none',
 'Feature_105_COECUsingClicks_add1thenlogthenmultiplyby1000',
 'Feature_105_ExpectedClicks_add1thenlogthenmultiplyby1000',
 'Feature_163_garbage1_none',
 'Feature_163_COECUsingClicks_add1thenlogthenmultiplyby1000',
 'Feature_163_ExpectedClicks_add1thenlogthenmultiplyby1000',
 'Feature_416_garbage1_none',
 'Feature_416_COECUsingClicks_add1thenlogthenmultiplyby1000',
 'Feature_416_ExpectedClicks_add1thenlogthenmultiplyby1000',
 'Feature_552_garbage1_none',
 'Feature_552_COECUsingClicks_add1thenlogthenmultiplyby1000',
 'Feature_552_ExpectedClicks_ad

In [37]:
flist = [x for x in list(df.columns) if 'Feature' in x]

In [56]:
df[flist].isnull().sum().sum()

0

In [15]:
meta_dict = {}
for fname in flist:
    meta_dict[fname] = {}
    meta_dict[fname]['min'] = df[fname].min()
    meta_dict[fname]['max'] = df[fname].max()

In [16]:
meta_dict

{'Feature_7604_garbage1_none': {'min': 0, 'max': 1},
 'Feature_7604_Impressions_log': {'min': 3912, 'max': 20203},
 'Feature_7604_NonClicksByClicksWithGBin_customizedlog': {'min': 1750,
  'max': 11346},
 'Feature_1_garbage1_none': {'min': 0, 'max': 1},
 'Feature_1_COECUsingClicks_add1thenlogthenmultiplyby1000': {'min': 12,
  'max': 2632},
 'Feature_1_ExpectedClicks_add1thenlogthenmultiplyby1000': {'min': 95,
  'max': 13338},
 'Feature_66_garbage1_none': {'min': 0, 'max': 1},
 'Feature_66_COECUsingClicks_add1thenlogthenmultiplyby1000': {'min': 20,
  'max': 2432},
 'Feature_66_ExpectedClicks_add1thenlogthenmultiplyby1000': {'min': 80,
  'max': 5841},
 'Feature_105_garbage1_none': {'min': 0, 'max': 1},
 'Feature_105_COECUsingClicks_add1thenlogthenmultiplyby1000': {'min': 96,
  'max': 1855},
 'Feature_105_ExpectedClicks_add1thenlogthenmultiplyby1000': {'min': 95,
  'max': 12972},
 'Feature_163_garbage1_none': {'min': 0, 'max': 1},
 'Feature_163_COECUsingClicks_add1thenlogthenmultiplyby1000

In [32]:
min_list = []
max_list = []
for fname in flist:
    min_list.append(int(df[fname].min()))
    max_list.append(int(df[fname].max()))

In [18]:
min_list

[0,
 3912,
 1750,
 0,
 12,
 95,
 0,
 20,
 80,
 0,
 96,
 95,
 0,
 80,
 95,
 0,
 37,
 87,
 0,
 84,
 95,
 0,
 178,
 52,
 0,
 83,
 95,
 0,
 96,
 95,
 0,
 94,
 95,
 0,
 77,
 95,
 0,
 134,
 95,
 0,
 64,
 95,
 0,
 345,
 5634,
 0,
 662,
 14305,
 0,
 339,
 4124,
 0,
 12,
 95,
 0,
 90,
 2078,
 0,
 76,
 95,
 0,
 64,
 95,
 0,
 55,
 95,
 0,
 67,
 95,
 0,
 66,
 95,
 0,
 67,
 95,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 499,
 8219,
 0,
 672,
 18006,
 0,
 631,
 6361,
 0,
 94,
 95,
 0,
 4,
 95,
 0,
 675,
 14650,
 0,
 605,
 12086,
 0,
 591,
 6361,
 0,
 514,
 6261,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 693,
 693,
 0,
 693,
 693,
 0,
 693,
 693,
 0,
 693,
 693,
 0,
 693,
 693,
 0,
 693,
 693]

In [21]:
id_feature = ["m:AdId", "m:OrderId", "m:CampaignId", "m:AdvertiserId", "m:ClientID", "m:TagId", "m:PublisherFullDomainHash", "m:PublisherId", "m:UserAgentNormalizedHash","m:DeviceOSHash"]

In [29]:
df[id_feature].values[0]

array([76965978384849, 1231453253691878, 401547031, 1757703,
       '2be2d56ca79d6f7d297cdbaca6616e97', 1059660833, 3149244597,
       17160724, '0e4d943ffd31c695dde3b356cb5fcd7d',
       'aea23489ce3aa9b6406ebb28e0cda430'], dtype=object)

In [23]:
idxdicts = []
for idname in tqdm(id_feature):
    cdict = {}
    idx = 0
    for v in df[idname]:
        if v not in cdict:
            cdict[v] = idx
            idx += 1
    idxdicts.append(cdict)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 239.32it/s]


In [24]:
idxdicts

[{76965978384849: 0,
  77309575421947: 1,
  73049048281320: 2,
  75454079227390: 3,
  72292922941800: 4,
  83975461502116: 5,
  83838036208871: 6,
  76622379285852: 7,
  78134187213137: 8,
  74217287837658: 9,
  75454119981983: 10,
  85075136885713: 11,
  77172012806392: 12,
  78271629052858: 13,
  81501372617286: 14,
  85281269185210: 15,
  85143908089842: 16,
  79989563044350: 17,
  77172047767842: 18,
  75041810526632: 19,
  78065473416278: 20,
  81157763896030: 21,
  80264470021184: 22,
  77996792719561: 23,
  77103413173407: 24,
  84112889717728: 25,
  72430495784658: 26,
  81295213230699: 27,
  78065431142899: 28,
  80951631927800: 29,
  79165013473074: 30,
  77927932560086: 31,
  85281289800431: 32,
  71124780015562: 33,
  79165013483082: 34,
  80882952346242: 35,
  76072593793912: 36,
  78409096516964: 37,
  82051208140487: 38,
  78821407700710: 39,
  81844977819649: 40,
  75797744401344: 41,
  77240796513484: 42,
  82257521344878: 43,
  79920803364035: 44,
  83219475904621: 45

In [41]:
infodict = {
    "faetures": flist,
    "minlist": min_list,
    "maxlist": max_list,
    "ids": id_feature,
    "dicts": idxdicts
}

In [34]:
json.dump(infodict, open(outp, "w"))

In [40]:
import torch.nn as nn

/home/hu/anaconda3/envs/cv/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [42]:
embs = nn.ModuleList([nn.Embedding(len(d), 20) for d in infodict['dicts']])

In [44]:
len(infodict['dicts'])

10

In [43]:
import torch

In [45]:
c = torch.randint(20, (32, 10))

In [49]:
embs[0](c[:, 0]).size()

torch.Size([32, 20])

In [57]:
df['m:Click'].value_counts()

0    9946
1      54
Name: m:Click, dtype: int64

In [88]:
label = torch.randint(0, 2, (32,)).type(torch.FloatTensor)

In [89]:
label

tensor([1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
        1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0.])

In [90]:
weight = torch.clone(label)
weight.masked_fill_(~weight.type(torch.BoolTensor), 1/20)

tensor([1.0000, 0.0500, 0.0500, 1.0000, 0.0500, 0.0500, 1.0000, 1.0000, 0.0500,
        1.0000, 1.0000, 1.0000, 1.0000, 0.0500, 1.0000, 1.0000, 0.0500, 1.0000,
        1.0000, 0.0500, 0.0500, 1.0000, 0.0500, 1.0000, 1.0000, 0.0500, 0.0500,
        0.0500, 0.0500, 1.0000, 1.0000, 0.0500])

In [91]:
weight

tensor([1.0000, 0.0500, 0.0500, 1.0000, 0.0500, 0.0500, 1.0000, 1.0000, 0.0500,
        1.0000, 1.0000, 1.0000, 1.0000, 0.0500, 1.0000, 1.0000, 0.0500, 1.0000,
        1.0000, 0.0500, 0.0500, 1.0000, 0.0500, 1.0000, 1.0000, 0.0500, 0.0500,
        0.0500, 0.0500, 1.0000, 1.0000, 0.0500])

In [92]:
label

tensor([1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
        1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0.])